import { ContentItem, MetricRecord, PriorityIssue, WeeklyReport } from "@/types";

export const DEMO_METRIC_PROVENANCE = {
  isDemo: true,
  sourceLabel: "DEMO SEED DATA — Disusun berdasarkan estimasi akun @iseeyou.glasses (Purwokerto)",
  date: "2026-09-14",
};

export const DEMO_HEADLINE_METRICS: MetricRecord[] = [
  {
    id: "m-followers",
    key: "followers",
    label: "Total Followers",
    value: 14820,
    unit: "akun",
    previousValue: 14210,
    deltaPercent: 4.3,
    date: "2026-09-14",
    source: "seed_demo",
    sourceLabel: "Instagram Insights (Simulasi)",
    isDemo: true,
    notes: "Pertumbuhan didorong oleh konten Reels POV Try-on kacamata bulat vintage",
  },
  {
    id: "m-reach",
    key: "weekly_reach",
    label: "Weekly Account Reach",
    value: 58430,
    unit: "akun unik",
    previousValue: 47200,
    deltaPercent: 23.8,
    date: "2026-09-14",
    source: "seed_demo",
    sourceLabel: "Instagram Insights (Simulasi)",
    isDemo: true,
    notes: "78% reach berasal dari non-followers di area Purwokerto & Banyumas",
  },
  {
    id: "m-engagement",
    key: "engagement",
    label: "Total Content Interactions",
    value: 4180,
    unit: "interaksi",
    previousValue: 3620,
    deltaPercent: 15.5,
    date: "2026-09-14",
    source: "seed_demo",
    sourceLabel: "Instagram Insights (Simulasi)",
    isDemo: true,
    notes: "Interaksi didominasi Saves dan Shares untuk katalog lensa & harga",
  },
  {
    id: "m-save-rate",
    key: "save_rate",
    label: "Avg Save Rate (Reels)",
    value: 6.4,
    unit: "%",
    previousValue: 4.8,
    deltaPercent: 33.3,
    date: "2026-09-14",
    source: "seed_demo",
    sourceLabel: "Manual Formula: (Saves / Reach) * 100",
    isDemo: true,
    notes: "Indikasi niat beli tinggi — audiens menyimpan referensi model frame",
  },
];

export const DEMO_PRIORITY_ISSUES: PriorityIssue[] = [
  {
    id: "p-1",
    type: "opportunity",
    title: "Reels format 'POV Try-on Frame' menghasilkan Save Rate 2.4× di atas rata-rata",
    description:
      "Video POV pemilihan frame sesuai bentuk muka lonjong menghasilkan 890 saves dari 18.200 reach. Format ini paling efektif menarik audiens mahasiswa Unsoed/Purwokerto.",
    impactMetric: "+33.3% Save Rate",
    suggestedAction: "Jadwalkan minimal 2 video POV per minggu dengan variasi bentuk wajah berbeda (bulat, kotak, oval).",
  },
  {
    id: "p-2",
    type: "concern",
    title: "Carousel promo diskon hard-selling mengalami penurunan reach -28%",
    description:
      "Feed grafis murni tentang 'Diskon Lensa 20%' hanya dijangkau 3.100 akun dengan komentar di bawah 10. Algoritma menekan konten berformat poster kaku.",
    impactMetric: "-28% Organic Reach",
    suggestedAction: "Ubah materi promo diskon menjadi video storytelling customer experience langsung di outlet Purwokerto.",
  },
  {
    id: "p-3",
    type: "observation",
    title: "Pertanyaan via DM didominasi estimasi waktu pasang lensa bluechromic di tempat",
    description:
      "Ada 42 DM masuk menanyakan apakah ganti lensa bisa ditunggu 20 menit langsung jadi di toko.",
    impactMetric: "42 Inbound Inquiries",
    suggestedAction: "Buat konten Reels 'Behind The Scene' proses faset lensa cepat di lab optik I See You.",
  },
];

export const DEMO_CONTENT_ITEMS: ContentItem[] = [
  {
    id: "c-01",
    title: "POV: Kamu cari frame kacamata yang cocok buat wajah bulat tapi gamau keliatan chubby",
    captionPreview:
      "Siapa bilang muka bulat ga bisa pake frame aesthetic? Ini 3 rekomendasi frame titanium tipis di Optik I See You Purwokerto yang langsung bikin rahang keliatan tirus! Free periksa mata ya bestie.",
    format: "reels",
    category: "POV Try-on & Styling",
    publishDate: "2026-09-12",
    reach: 24300,
    likes: 1840,
    comments: 86,
    saves: 1120,
    shares: 430,
    engagementRate: 14.3,
    saveRate: 4.6,
    rank: 1,
    isDominantPerformer: true,
    thumbnail: "/lokasi/purwokerto/IMG_1544.webp",
    branchName: "Purwokerto (Pusat)",
    keyObservation: "Top performer minggu ini. Audiens relate dengan problem bentuk wajah; save rate sangat tinggi.",
    source: "seed_demo",
    isDemo: true,
  },
  {
    id: "c-02",
    title: "Edukasi Lensa: Perbedaan Blue Ray biasa vs Bluechromic Transition pas kena matahari",
    captionPreview:
      "Banyak yang bingung bedanya kacamata anti radiasi biasa sama bluechromic. Kita uji langsung di bawah terik matahari Purwokerto jam 12 siang!",
    format: "reels",
    category: "Edukasi Lensa & Produk",
    publishDate: "2026-09-10",
    reach: 16800,
    likes: 920,
    comments: 54,
    saves: 780,
    shares: 210,
    engagementRate: 11.7,
    saveRate: 4.6,
    rank: 2,
    thumbnail: "/lokasi/cilacap/IMG_6716.webp",
    branchName: "Cilacap",
    keyObservation: "Menjawab keraguan teknis customer sebelum datang ke toko. Memicu 18 pertanyaan DM tentang harga paket.",
    source: "seed_demo",
    isDemo: true,
  },
  {
    id: "c-03",
    title: "Carousel: 5 Koleksi Frame Korean Minimalist Masuk Restock Minggu Ini (Under 250k)",
    captionPreview:
      "Slide 1 sampai 5 frame mana yang paling kamu taksir? Stok terbatas ya, mampir ke outlet Optik I See You Jl. HR Boenyamin Purwokerto!",
    format: "carousel",
    category: "Katalog & Restock",
    publishDate: "2026-09-09",
    reach: 9400,
    likes: 460,
    comments: 31,
    saves: 340,
    shares: 88,
    engagementRate: 9.8,
    saveRate: 3.6,
    rank: 3,
    thumbnail: "/lokasi/purbalingga/IMG_8526.webp",
    branchName: "Purbalingga",
    keyObservation: "Carousel bekerja baik untuk audiens yang ingin mengecek foto detail frame dan spek ukuran bridge/nosepad.",
    source: "seed_demo",
    isDemo: true,
  },
  {
    id: "c-04",
    title: "Behind The Scenes: Proses potong dan pasang lensa kacamata silinder tinggi rapi & presisi",
    captionPreview:
      "Minus 5.00 silinder 2.00 tetap bisa tipis dan manis kalau pemilihan indeks lensanya tepat. Tim lab optik kita siap bantu ukur pupil distance kamu gratis.",
    format: "reels",
    category: "Otoritas & Lab Optik",
    publishDate: "2026-09-08",
    reach: 7800,
    likes: 380,
    comments: 24,
    saves: 190,
    shares: 64,
    engagementRate: 8.4,
    saveRate: 2.4,
    rank: 4,
    thumbnail: "/lokasi/purwokerto/IMG_1543.webp",
    branchName: "Purwokerto (Lab)",
    keyObservation: "Membangun kepercayaan terhadap keahlian refraksi optik, bukan sekadar jualan frame estetik.",
    source: "seed_demo",
    isDemo: true,
  },
  {
    id: "c-05",
    title: "Feed Single Image: Pengumuman Jadwal Refraksionis Optik I See You Minggu Ini",
    captionPreview:
      "Jangan tunda periksa mata ya! Cek jadwal pemeriksaan lengkap bareng refraksionis berlisensi kami.",
    format: "feed",
    category: "Operasional Toko",
    publishDate: "2026-09-13",
    reach: 2600,
    likes: 85,
    comments: 4,
    saves: 18,
    shares: 7,
    engagementRate: 4.4,
    saveRate: 0.7,
    rank: 5,
    thumbnail: "/lokasi/wonosobo/IMG_4474.webp",
    branchName: "Wonosobo",
    keyObservation: "Format poster single image organik memiliki distribusi terendah. Ke depan informasi jadwal lebih pas ditaruh di Story/Highlights.",
    source: "seed_demo",
    isDemo: true,
  },
];

export const DEMO_HISTORICAL_TRENDS = [
  { week: "W33", reach: 38200, interactions: 2650, saves: 1100, followersGained: 180 },
  { week: "W34", reach: 41900, interactions: 2980, saves: 1350, followersGained: 240 },
  { week: "W35", reach: 45600, interactions: 3200, saves: 1620, followersGained: 310 },
  { week: "W36", reach: 47200, interactions: 3620, saves: 1980, followersGained: 420 },
  { week: "W37 (Current)", reach: 58430, interactions: 4180, saves: 2450, followersGained: 610 },
];

export const DEMO_FORMAT_PERFORMANCE = [
  { format: "Reels POV / Try-on", avgReach: 20550, avgSaveRate: 4.6, totalPosts: 6 },
  { format: "Edukasi Lensa (Reels)", avgReach: 14200, avgSaveRate: 4.1, totalPosts: 3 },
  { format: "Carousel Restock Frame", avgReach: 8600, avgSaveRate: 3.4, totalPosts: 4 },
  { format: "Feed Poster / Jadwal", avgReach: 2750, avgSaveRate: 0.8, totalPosts: 2 },
];

export const DEMO_WEEKLY_REPORT: WeeklyReport = {
  id: "rep-w37-2026",
  weekNumber: 37,
  periodLabel: "Week 37 · 8–14 September 2026",
  startDate: "2026-09-08",
  endDate: "2026-09-14",
  status: "reviewed",
  executiveSummary:
    "Performa marketing Optik I See You minggu ini mencatat pertumbuhan reach tertinggi bulan ini (+23.8%), didorong oleh transisi format konten dari poster promosi ke video Reels POV Try-on kacamata dan edukasi lensa di outlet Purwokerto. Save-to-reach ratio meningkat ke 6.4%, menandakan minat beli calon konsumen lokal semakin terarah.",
  headlineMetrics: {
    totalFollowers: DEMO_HEADLINE_METRICS[0],
    weeklyReach: DEMO_HEADLINE_METRICS[1],
    totalEngagements: DEMO_HEADLINE_METRICS[2],
    saveToReachRatio: DEMO_HEADLINE_METRICS[3],
  },
  pencapaian: [
    "Total jangkauan mingguan tembus 58.430 akun (+23.8% WoW), dengan 78% merupakan non-followers di wilayah Purwokerto dan sekitarnya.",
    "Konten Reels 'POV Wajah Bulat' menjadi top performer dengan 24.300 reach dan 1.120 saves (save rate 4.6%).",
    "Peningkatan inbound DM pertanyaan produk dan jadwal cek mata gratis naik 34% (total 62 percakapan baru).",
    "Konsistensi posting target tercapai: 14 konten feed/reels terbit sepanjang Selasa–Sabtu sesuai jadwal tim konten.",
  ],
  kendala: [
    "Materi feed statis bertema poster diskon mengalami penurunan engagement tajam (reach rata-rata di bawah 3.000).",
    "Keterbatasan pencahayaan saat syuting video demonstrasi lensa di lab dalam toko saat sore hari.",
    "Belum adanya template pencatatan real-time antara traffic konten Instagram dengan customer yang datang langsung menanyakan frame tertentu di toko.",
  ],
  planStrategi: [
    "Menghentikan produksi poster feed kaku, menggantinya dengan Reels storytelling interaksi kasir/refraksionis dengan customer.",
    "Memproduksi seri mingguan: 'POV Kacamata Sesuai Jurusan Kuliah' (menargetkan mahasiswa Unsoed, UMP, Telkom Purwokerto).",
    "Menambah 1 set ring light portabel di area lab faset agar detail kejernihan lensa terlihat jelas di kamera.",
    "Menguji program kode voucher khusus di caption Instagram untuk melacak konversi pengunjung offline.",
  ],
  masukanTim: [
    "Masukan untuk HRD & Management: Jadwal syuting konten direkomendasikan di jam toko agak tenang (10.00 - 12.00 WIB) agar tidak mengganggu antrean periksa mata pelanggan.",
    "Masukan untuk Finance: Alokasi budget kecil (Rp 150.000/minggu) untuk uji coba boost post pada konten edukasi lensa yang sudah terbukti memiliki save rate di atas 4%.",
    "Masukan untuk Tim Toko: Mengingatkan staf front-liner untuk selalu menanyakan 'tahu Optik I See You dari mana kak?' saat proses transaksi kacamata.",
  ],
  aiAnalysis: [
    {
      id: "ai-1",
      tag: "FAKTA",
      text: "Reels format POV styling kacamata menghasilkan 4.6% save rate, sedangkan Feed promo statis hanya menghasilkan 0.7% save rate.",
      metricBasis: "Data performa posting Week 37",
    },
    {
      id: "ai-2",
      tag: "INTERPRETASI",
      text: "Audiens target lokal Purwokerto lebih merespons rekomendasi gaya personal dan problem-solving bentuk wajah dibanding sekadar penawaran potongan harga langsung.",
      metricBasis: "Rasio Saves dan Comments pada c-01 dan c-02",
    },
    {
      id: "ai-3",
      tag: "REKOMENDASI",
      text: "Alokasikan 70% slot konten mingguan untuk Reels POV & Edukasi, 20% Carousel foto katalog frame close-up, dan alihkan 10% sisa slot ke Instagram Story harian.",
      metricBasis: "Benchmarking efektivitas format mingguan",
    },
  ],
};
